name: Generate Types

on:
  push:
    branches:
      - master
      - 'feature/**'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
            
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
          dotnet-quality: ga

      - name: Install OpenVR Dependencies
        shell: cmd
        run: |
          call cd EasyOpenVR
          call download_openvr_api_dependencies.cmd

      - name: Install dependencies
        run: dotnet restore

      - name: Restore local tools
        run: dotnet tool restore

      - name: Build
        run: dotnet build OpenVR2WS/OpenVR2WS.csproj --configuration Release --runtime win-x64

      - name: Generate TypeScript
        run: dotnet dotnet-typegen generate -p OpenVR2WS
        
      - name: LS
        run: |
          ls
          cd types
          ls

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Types
          path: ./types